#!/bin/bash
set -e
source build.env

echo "======================================================="
echo "   [6/7] Finalizing and Sealing Pure Ubuntu Images"
echo "======================================================="
ROOTFS_DIR="Ubuntu-Beryllium"
BOOT_IMG="ubuntu_beryllium_boot.img"
ROOT_IMG="ubuntu_beryllium_root.img"

# Ensure clean mounts
for d in run sys proc dev/pts dev; do
    if mountpoint -q "$ROOTFS_DIR/$d"; then
        sudo umount -l "$ROOTFS_DIR/$d"
    fi
done

# -----------------------------------------
# Step 1: UUID Generation & Fstab Injection
# -----------------------------------------
BUILD_UUID=$(uuidgen)
echo ">>> Generated Master UUID: $BUILD_UUID"
echo "ROOTFS_UUID=$BUILD_UUID" >> build.env

FSTAB_FILE="$ROOTFS_DIR/etc/fstab"
sudo bash -c "echo '# Generated by Ubuntu Desktop Pocket Edition Toolkit' > $FSTAB_FILE"
sudo bash -c "echo 'UUID=$BUILD_UUID / ext4 errors=remount-ro 0 1' >> $FSTAB_FILE"

# -----------------------------------------
# Step 2: Harvest Boot Assets
# -----------------------------------------
KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz-* | tail -n 1)
INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-* | tail -n 1)
# Locate Beryllium DTB (usually in /usr/lib/linux-image-*/qcom/ on Debian/Mobian roots)
DTB=$(find "$ROOTFS_DIR/usr/lib" -type f -name "sdm845-xiaomi-beryllium.dtb" | head -n 1)

if [[ -z "$DTB" ]]; then
    DTB=$(find "$ROOTFS_DIR/boot" -type f -name "sdm845-xiaomi-beryllium.dtb" | head -n 1)
fi

if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
    echo "ERROR: Missing Kernel, Initramfs, or DTB! Cannot pack boot.img."
    exit 1
fi

echo ">>> Harvested Assets:"
echo "Kernel: $(basename "$KERNEL")"
echo "Initrd: $(basename "$INITRD")"
echo "DTB:    $(basename "$DTB")"

# -----------------------------------------
# Step 3: Forge boot.img
# -----------------------------------------
echo ">>> Packing boot.img..."
mkbootimg \
  --kernel "$KERNEL" \
  --ramdisk "$INITRD" \
  --dtb "$DTB" \
  --pagesize 4096 \
  --base 0x00000000 \
  --kernel_offset 0x00008000 \
  --ramdisk_offset 0x01000000 \
  --tags_offset 0x00000100 \
  --cmdline "root=UUID=${BUILD_UUID} rw rootwait console=tty0 console=ttyMSM0,115200n8 earlycon=qcom_geni,0x00A90000 PMOS_NOSPLASH" \
  -o "$BOOT_IMG"

# -----------------------------------------
# Step 4: Burn RootFS to Sparse Image
# -----------------------------------------
if ! command -v img2simg &> /dev/null; then
    sudo apt-get install -y android-sdk-libsparse-utils || sudo apt-get install -y android-tools-fsutils
fi

IMG_MB=$((IMAGE_SIZE * 1024))
echo ">>> Burning RootFS to Raw Ext4 (${IMAGE_SIZE}GB)..."

# mke2fs directly formats and copies the rootfs directory, burning the UUID into the geometry
sudo mke2fs -t ext4 -U "$BUILD_UUID" -d "$ROOTFS_DIR" "$ROOT_IMG" "${IMG_MB}M"

echo ">>> Converting to sparse image for fastboot..."
ROOT_SPARSE="${ROOT_IMG%.img}_sparse.img"
img2simg "$ROOT_IMG" "$ROOT_SPARSE"

echo "======================================================="
echo ">>> FLASHING INSTRUCTIONS:"
echo ">>> 1. fastboot flash boot $(pwd)/$BOOT_IMG"
echo ">>> 2. fastboot flash userdata $(pwd)/$ROOT_SPARSE"
echo "======================================================="
