[Mobuntu L4T]
l4t=1
boot_prefixes=/switchroot/mobuntu/
id=SWR-MOB
uart_port=0
r2p_action=self
icon=switchroot/mobuntu/icon.bmp
logopath=switchroot/mobuntu/bootlogo.bmp
# Optional fields you can uncomment:
# emmc=1                 ; enable eMMC partition support
# usb3_enable=1          ; max USB speeds (degrades 2.4GHz BT/WiFi signal)
# rootlabel_retries=100  ; retry rootdev search 100 * 200ms = 20s (USB boot)
# rootdev=mmcblk0p2      ; explicit rootdev (overrides id-based search)
