# Mobuntu-L4T — LightDM configuration
# File: overlays/etc/lightdm/lightdm.conf.d/50-mobuntu.conf
# UI selection is set by apply-overlays.sh at build time

[Seat:*]
autologin-guest=false
autologin-user=mobuntu
autologin-user-timeout=0
autologin-session=phosh
user-session=phosh
